module.exports = {
  apps: [
    {
      name: 'sheep-backend',
      script: './dist/main.js',
      cwd: '/root/sheep-game/backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '400M',
      env: {
        NODE_ENV: 'production',
        PORT: 4001,
      },
      error_file: '/root/sheep-game/logs/backend-error.log',
      out_file: '/root/sheep-game/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
    {
      name: 'sheep-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/root/sheep-game/frontend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      error_file: '/root/sheep-game/logs/frontend-error.log',
      out_file: '/root/sheep-game/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
    {
      name: 'sheep-admin',
      script: 'npm',
      args: 'run preview -- --port 4002',
      cwd: '/root/sheep-game/admin',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/sheep-game/logs/admin-error.log',
      out_file: '/root/sheep-game/logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
  ],
};
